### ISSUE TITLE
HTTPS Header Behind SSL-Terminating LoadBalancer

### ISSUE THREAD

**Issue by gveltri** [simplerisk/code#24]
Hi,

Thanks for open sourcing this project! It's been very useful for our small company.

I've been using the dockerized version of the app behind a load-balancer that's terminating SSL and passing unencrypted traffic to the webserver. The `HTTPS` $_SERVER environment variable is currently determining the protocol that ajax requests will be templated as. This header is not robust enough to handle forwarded HTTPS. The `X-FORWARDED-PROTO` header should be tested as well as `HTTPS`.

See the following Stack Overflow answer for more details on implementation: https://stackoverflow.com/a/16076965 .

I'm more than willing to implement and merge request!

**Comment by gveltri** [comment]
For anyone that has this issue and doesn't want to edit the source code, defining my apache config like so got it to work albeit a bit inelegantly.

```
<VirtualHost *:80>
        Header always set HTTPS "on"
        DocumentRoot /var/www/simplerisk
        <Directory "/var/www/simplerisk">
                AllowOverride all
                allow from all
                Options -Indexes
        </Directory>
        RewriteEngine Off
</VirtualHost>
```

**Comment by jsokol** [comment]
Hey Gerardo!  Thanks for the feedback and letting us know about this issue.  We run docker containers behind a load-balancer, but never ran into this since we do not terminate SSL at the load balancer and run it all the way to the server.  In any case, this is good to know if we have customers who run into this and your workaround to include setting the HTTPS headers is a good one.  I'm glad that fixed it for you and that shouldn't affect your SimpleRisk functionality at all or your ability to upgrade it in the future, so that's positive.  

The next release of SimpleRisk does make some changes to how URLs are set and we rely more heavily on the SimpleRisk Base URL value set in the configuration in order to avoid potential security issues.  I think this change potentially alleviates concerns around using $_SERVER.  Let's hold this bug report open until the next release drops (expected in March 2020) and we can validate and take it from there.  Again, thanks for reaching out!  I'm happy to hear SimpleRisk has been useful for you and your company!

**Comment by anthonyjsargeant** [comment]
@jsokol Did this functionality make it into the current release, as we're having the same issue, albeit with the solution @gveltri not working for us.

We're seeing a `500` error once you get passed the login screen, so there's something in that config that our deployment isn't happy about.

**Comment by anthonyjsargeant** [comment]
I realised what my problem was; I needed to update the DB schema. So it's all working! 😄

**Comment by jsokol** [comment]
@anthonyjsargeant Sorry for the delay in getting back to you.  Yes, the 500 error is because there are new user permissions included in the release and a normal login without the updated database doesn't know how to handle them.  When you go to /admin/upgrade.php, it does a login for only an admin user, using none of the new permissions, and allows you to upgrade the database schema.  With an upgraded schema, all should be good.  Just as a FYI, we are currently tracking an issue with grouping in the Dynamic Risk Report in the new release and will likely be rolling a new release later today to address that bug.
