### ISSUE TITLE
DataTables warning: table id=framework-controls - Ajax error. For more information about this error, please see http://datatables.net/tn/7

### ISSUE THREAD

**Issue by rverrips** [simplerisk/code#29]
`DataTables warning: table id=framework-controls - Ajax error. For more information about this error, please see http://datatables.net/tn/7` as a javascript alert. 

![Screen Shot 2022-04-13 at 1 26 06 PM](https://user-images.githubusercontent.com/749015/163246122-ba5b5361-d50b-4c51-903f-5082fb3a5594.png)

I receive the above error when selecting any options under the "Compliance" menu of a fresh install (i.e. when selecting "Define Tasks", "Initiate Audits", "Active Audits" and "Past Audits" 

This is a fresh installation (cloned simplerisk/code repo and ran web installer) on:
Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-1009-aws x86_64)
php 7.4.28
mysql 8.0.28
nginx 1.20.2

Error in browser console is:
`Failed to load resource: the server responded with a status of 404 () https://<my_hostname>/api/compliance/reports/index.php`

**Comment by jsokol** [comment]
Hey Roy.  Sorry for the issue.  Typically for a stock system like this, we would recommend using the scripted installation, since it ensures that all of the proper configurations are put in place.  In your case, it sounds like maybe you missed a step in the self-install process where it talks about creating the configuration that allows SimpleRisk to communicate with its API.  You can find instructions on how to do this for your Nginx environment [here](https://simplerisk.freshdesk.com/a/solutions/articles/6000156754), but I'd highly recommend taking a look at your health check (Configure -> Health Check) for any other configurations you may have missed.

**Comment by rverrips** [comment]
>It sounds like maybe you missed a step in the self-install process where it talks about creating the configuration that allows SimpleRisk to communicate with its API. You can find instructions on how to do this for your Nginx environment [here](https://simplerisk.freshdesk.com/a/solutions/articles/6000156754)

Dear @jsokol 

Thanks for the prompt reply, and indeed I was looking to find an NGINX alternative to the .htaccess in the /api folder.

>  I'd highly recommend taking a look at your health check (Configure -> Health Check) for any other configurations you may have missed.

The only item that shows as disabled in the health check is the connectivity -> SimpleRisk API ... I'll keep working on it though now that I know what the issue is.   

I really do appreciate the help you provided!

**Comment by jsokol** [comment]
That's great to hear!  If you have any other questions, please feel free to reach out to Support.  And we'd love to do a demo for you when you're ready.
