### ISSUE TITLE
Invalid base url error even when its valid

### ISSUE THREAD

**Issue by kakumanivrn** [simplerisk/code#41]
I think the issue in not just with base url but the HTTPS verification in many places. If someone is setting this up in a Kubernetes environment, the ingress would terminate SSL after passing through ingress. And users access the Simplerisk using ingress as frontend with HTTPS.

For example in `code/simplerisk/includes/functions.php` the function `is_valid_base_url` always returns false if you try to change the base URL with HTTPS link (even if the Load Balancer / K8s Ingress is using HTTPS for the end user). 

I think it would make it much easier for Simplerisk and also for end users to remove all the HTTPS verifications in the code. A k8s manifest could be provided to users which handles SSL service.

**Comment by jsokol** [comment]
Hello.  We actually run the code and these images in a Kubernetes environment with ingress and do not have this issue with the is_valid_base_url function returning false.  The solution is to actually run SSL (even if self-signed certificate) on the container, so that the URL it receives matches the URL that is being used.  This verification is used for security purposes and we do not intend to change how it is handled or remove it from the product, but we do appreciate your suggestion.
