### ISSUE TITLE
Data table issue

### ISSUE THREAD

**Issue by kundan333** [simplerisk/code#51]
![Screenshot from 2024-12-23 17-07-51](https://github.com/user-attachments/assets/f584ac02-b420-4409-adf1-52e55290e603)

After fresh install. I am getting this.

**Comment by jsokol** [comment]
Hello @kundan333.  I'm sorry to hear about the issue you are experiencing.  Can you please help provide some additional information for us to use to troubleshoot this issue?

1. What installation method did you use for this instance?
2. What version of SimpleRisk is this running (you can see this under Configure -> About)?
3. Are there any red X's under the Configure -> Health Check menu (please provide a screenshot)?
4. Is this immediately after you installed or did you happen to do an assessment (we have an open issue on this happening there)?

Thank you.

**Comment by jsokol** [comment]
@kundan333 I spoke with our development team and they said that the issue which we've already identified had to do with the mitigation percent value.  It has been fixed in the 20241209-001 release.  Let's verify that you are at this release (see #2 in my previous response) and we can determine whether additional troubleshooting is necessary, from there.  Thanks.

**Comment by jsokol** [comment]
Assuming that this is the issue, you can also disable the mitigation percent field via the "Settings" cog and see if the report resolves after that.

![image](https://github.com/user-attachments/assets/69341072-9048-4f06-ab88-61dad78745b5)

**Comment by kundan333** [comment]
Hi @jsokol ,

Thank you for your response.

Here are some details

*> I am using Ubuntu.

*> I don't see  mitigation percent field.
![Screenshot from 2024-12-24 12-49-25](https://github.com/user-attachments/assets/61ce3c90-0917-422e-92d0-87b1763dcf49)


*> Here is the site health (I think there is issue with API routes or something)
![Screenshot from 2024-12-24 12-50-37](https://github.com/user-attachments/assets/17c1977b-b443-4370-8286-63f1578b3084)


*> I am using the latest version
![Screenshot from 2024-12-24 12-50-47](https://github.com/user-attachments/assets/84591b8d-327b-472c-aa46-80586d94d1de)

**Comment by kundan333** [comment]
I think site health is fine there is issue with API only

![Screenshot from 2024-12-24 13-22-15](https://github.com/user-attachments/assets/6519aea8-6282-48fa-bcef-380c85776f5f)


![Screenshot from 2024-12-24 13-22-23](https://github.com/user-attachments/assets/fe633d48-cb95-4b55-924e-2bf50744a57d)

**Comment by jsokol** [comment]
@kundan333 If I had to guess, the SimpleRisk environment does not have the ability to resolve "localhost".  You might try 127.0.0.1, instead, or better yet give the system a proper domain name.  Make sure that you update the SimpleRisk Base URL value under Configure -> Settings.

You did not answer my question about which installation method you used, only that you installed it on Ubuntu, so my assumption is that you used the "Manual Installation" method, which is discouraged due to issues like these.  For configuration support, I'd recommend one of our standard support methods listed under the HELP icon in the top right corner of your SimpleRisk instance.  Since this is not a code issue, I am closing it out here.
