### ISSUE TITLE
Erroneus link

### ISSUE THREAD

**Issue by Aiki-Kai** [simplerisk/code#8]
In the CVSS risk scoring edit page there is this text "Full details of CVSS Version 2.0 scoring can be found here. "
Dead link: https://www.first.org/cvss/cvss-guide.html
Working URL: https://www.first.org/cvss/cvss-v30-user_guide_v1.4.pdf or https://www.first.org/cvss/user-guide

**Comment by jsokol** [comment]
Thank you for reporting this issue.  It looks like they moved the link when they released CVSSv3.  Since this is technically CVSSv2, not CVSSv3, the correct link should be https://www.first.org/cvss/v2/guide.  I've updated the code in our development environment and it will be fixed in the next release (likely before the end of December).
