### ISSUE TITLE
Xss in uploading Supporting Documentation

### ISSUE THREAD

**Issue by Iampwned** [simplerisk/code#9]
I found an XSS issue on Supporting Documentation 
![screenshot from 2017-07-29 12-03-20](https://user-images.githubusercontent.com/25719480/28742761-6db9c488-7456-11e7-8c46-d72df6199796.png)

Xss in image name
Files used
`
"><img src=1 onerror=alert(document.domain)> .jpg
`

**Comment by jsokol** [comment]
The code has an htmlencoding of that file name value so I'm not entirely sure where the issue lies, but we are looking into it and should have it fixed for the next release.  Thank you for reporting!

**Comment by jsokol** [comment]
The issue has been identified and fixed in our development branch and the fix will be included in the next release of SimpleRisk.  I have added you to our Contributors page to thank you for your contribution.  https://www.simplerisk.com/contributors  We appreciate your responsible disclosure of this vulnerability!

**Comment by jsokol** [comment]
This issue has been addressed in the 20180104-001 release of SimpleRisk.  Thank you!
